### PR TITLE
and/c: use projections more on flat-contract arguments

### PR DESCRIPTION
**Pull request by AlexKnauth**
Should fix the problem outlined here:
http://www.mail-archive.com/racket-users@googlegroups.com/msg27144.html
http://www.mail-archive.com/racket-users@googlegroups.com/msg27163.html

### CODE REVIEW

**Comment by rfindler** [comment]
Can you add a test case somewhere to demonstrate the difference with this change? Maybe in `tests/racket/contract/context` ?

**Comment by AlexKnauth** [comment]
I added a test in `tests/racket/contract/context.rkt` and fixed another test in `tests/racket/contract/or-and.rkt`.

**Comment by lexi-lambda** [comment]
I haven't tested this or looked it over in detail, but the premise of the change looks good to me.

**Comment by rfindler** [comment]
I've pushed this. Does it help, Alexis?

**Comment by lexi-lambda** [comment]
Yep, this works well! Thanks to both of you. I'll tweak my own error message slightly to fit this better, but this is definitely what I was looking for.

**Pull request closed without merging**
