### PR TITLE
Allow user to set there personal github api token

### PR DESCRIPTION
**Pull request by LeifAndersen**
Using the PLT_GITHUB_API_KEY environment variable.

### CODE REVIEW

**Comment by samth** [comment]
_their_!

**Comment by mflatt** [comment]
@LeifAndersen Are you running into GitHub query limits? I think I ran into that problem a week or two ago, and I have been thinking that we should switch `raco pkg` to always use the Git protocol, instead of using GitHub API queries.

**Comment by samth** [comment]
I've run into the API limits, such as with `raco pkg update -a` run repeatedly.

**Comment by LeifAndersen** [comment]
@samth Doah.

@mflatt Yes, I run into them quite regularly when updating.

**Comment by stamourv** [comment]
Ditto. The limits make `raco pkg catalog-archive` unreliable, too.

**Comment by mflatt** [comment]
@LeifAndersen I changed `raco pkg` to use the Git protocol for GitHub. Are you still interested in adding `PLT_GITHUB_API_KEY`?

**Comment by LeifAndersen** [comment]
Cool, thanks.

Nah, I'm not really interested then. I only cared because we were hitting the API rate limit, and if that's not a problem any more then I don't care.

Thanks for pushing this.

**Pull request closed without merging**
