### PR TITLE
Merge part of `unstable/sequence` with `racket/sequence`

### PR DESCRIPTION
**Pull request by stamourv**
Merges `in-syntax`, `in-pairs` and `in-slice` to `racket/sequence`.

Leaves `sequence-lift` and `in-sequence-forever` in `unstable/sequence`, which will leave the main distribution. The former is redundant given `sequence-map`, and the latter is not used very much (and doesn't have a good name).

### CODE REVIEW

**Comment by soegaard** [comment]
> Merges in-syntax, in-pairs and in-slice to racket/sequence.

Before moving in-pairs to racket/sequence I'd like argue that the current
in-pairs
is doing the wrong thing. I expect in-pairs to loop over the spine of a
line.

From an old email:

I'd like to lobby that in-pairs is the following,
wherein the clause [p (in-pairs '(1 2 3))] lets binds p
to the pairs of the list.

(define (in-pairs xs)
  (make-do-sequence
   (λ ()
     (define (pos->element p) p)
     (define (next-position p) (cdr p))
     (define initial-position xs)
     (define (continue-with-pos? p) (pair? p))
     (values pos->element
             next-position
             initial-position
             continue-with-pos?
             #f #f))))

Examples:

>* (for ([p (in-pairs '(1 2 3 4))])
*    (displayln p))
(1 2 3 4)
(2 3 4)
(3 4)
(4)


(define (deltas xs)
  (for/list ([p (in-pairs xs)]
             #:when (pair? (cdr p)))
    (- (cadr p) (car p))))

>* (deltas '(1 3 7 13))
*'(2 4 6)


Further discussion:
   http://lists.racket-lang.org/users/archive/2012-December/055531.html


2015-08-09 16:39 GMT+02:00 Vincent St-Amour <notifications@github.com>:

> Merges in-syntax, in-pairs and in-slice to racket/sequence.
>
> Leaves sequence-lift and in-sequence-forever in unstable/sequence, which
> will leave the main distribution. The former is redundant given
> sequence-map, and the latter is not used very much (and doesn't have a
> good name).
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/plt/racket/pull/1002
> Commit Summary
>
>    - Make doc section title more accurate.
>    - Improve the implementation of `in-slice`.
>    - Merge part of unstable/syntax with racket/syntax.
>    - Move rest of unstable/sequence to unstable-lib.
>    - Move docs for part of `unstable/sequence` to the `racket/sequence`
>    docs.
>    - Improve docs for the new bits of `racket/sequence`.
>    - Move tests for the new bits of `racket/sequence` from
>    `unstable/sequence` tests.
>    - Add more tests.
>
> File Changes
>
>    - *M* pkgs/racket-doc/scribblings/reference/sequences.scrbl
>    <https://github.com/plt/racket/pull/1002/files#diff-0> (36)
>    - *M* pkgs/racket-test-core/tests/racket/sequence.rktl
>    <https://github.com/plt/racket/pull/1002/files#diff-1> (22)
>    - *M* racket/collects/racket/match/define-forms.rkt
>    <https://github.com/plt/racket/pull/1002/files#diff-2> (2)
>    - *M* racket/collects/racket/sequence.rkt
>    <https://github.com/plt/racket/pull/1002/files#diff-3> (48)
>    - *D* racket/collects/unstable/sequence.rkt
>    <https://github.com/plt/racket/pull/1002/files#diff-4> (83)
>
> Patch Links:
>
>    - https://github.com/plt/racket/pull/1002.patch
>    - https://github.com/plt/racket/pull/1002.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plt/racket/pull/1002>.
>



-- 
-- 
Jens Axel Søgaard

**Comment by stamourv** [comment]
I have since changed my mind re including `in-pairs`, as `in-dict` is more general, and gets specialized by `for`. `in-pairs` will stay in `unstable/sequence` and leave the main distribution. I just forgot to update the PR.

What you're suggesting is a different function (which I'd call something like `in-tails`), which could also be a nice addition to `racket/sequence`. I'd suggest opening a new issue / PR for it, as it's a separate discussion IMO.

**Comment by stamourv** [comment]
Oh, also, leaving `in-pairs` out of `racket/sequence` does keep the name "open" for what you're suggesting, though there is still code out there that use `unstable/sequence`'s `in-pairs`.

**Comment by stamourv** [comment]
Merged

**Pull request closed without merging**
