### PR TITLE
on generic method error, mention other args

### PR DESCRIPTION
**Pull request by stchang**
Don't merge. @rfindler, is this what you had in mind?

### CODE REVIEW

**Comment by samth** [comment]
@stchang @rfindler what's the status here?

**Comment by rfindler** [comment]
This looks like a good improvement in the error messages to me!

If you wanted to do more, I bet you could put the names of the arguments
into the messages and maybe put an * next to the ones that have default
values?

Robby

**Comment by stchang** [comment]
> I bet you could put the names of the arguments into the messages and maybe put an * next to the ones that have default values?

I dont see an easy way to do this unless I roll my own error msg formatting. I could use `raise-arguments-error` but then we would lose the position information. I'll explore some thing and report back.

**Comment by rfindler** [comment]
On Thursday, March 12, 2015, Stephen Chang <notifications@github.com> wrote:

> I bet you could put the names of the arguments into the messages and maybe
> put an * next to the ones that have default values?
>
> I dont see an easy way to do this unless I roll my own error msg
> formatting.
>
>
Right.



> I could use raise-arguments-error but then we would lose the position
> information. I'll explore some thing and report back.
>

I think what you have done is great and if you want to push it will help
people today.

If you wanted to make a better version of r-a-e that also worked for
keyword functions separately that would be double great!

**Comment by stchang** [comment]
I agree there's still room for improvement. Is `raise-argument-error` and `raise-arguments-error` implemented in Racket? I can't seem to find it.

**Comment by rfindler** [comment]
It's "do_raise_error" in src/racket/src/error.c.

**Comment by stchang** [comment]
Ok I see it, thanks.

**Comment by stchang** [comment]
I improved the error message, by manually formatting it using `raise-arguments-error`. It reports all optional and keyword arguments and labels them. The drawback is that the "other" args ellipses cannot be hidden. Also, the position is displayed as just an index and not an ordinal. If this is ok, I'll merge.

```
#lang racket
(require racket/generic)
(define-generics AA
  [meth1 a AA c [d] [e] #:reqkw req #:optkw [optkw]]
  [meth2 f g AA . restargs])
(meth1 "1" 'notAA 5 #:reqkw 4)
```
=>
```
meth1: contract violation:
expected: AA?
given: 'notAA
argument (0-base) pos: 1
other arguments...:
  a: "1"
  c: 5
  d (optional): 'default-arg850
  e (optional): 'default-arg850
  #:reqkw: 4
  #:optkw (optional): 'default-arg850
```

`(meth2 5 6 7 8 9 10)` 
=>
```
meth2: contract violation:
expected: AA?
given: 7
argument (0-base) pos: 2
other arguments...:
  f: 5
  g: 6
  rest args: '(8 9 10)
```

**Comment by rfindler** [comment]
That looks great!!!

Arguments are base one in most other places, tho, so maybe change that?

-> (+ 1 'x 2)

; +: contract violation

;   expected: number?

;   given: 'x

;   argument position: 2nd

; [,bt for context]


-> (define/contract (f x y) (-> integer? integer? integer?) (+ x y))

-> (f 1 'x)

; f: contract violation

;   expected: integer?

;   given: 'x

;   in: the 2nd argument of

;       (-> integer? integer? integer?)

;   contract from: (function f)

;   blaming: top-level

;    (assuming the contract is correct)

;   at: readline-input:2.18

; [,bt for context]



Robby

**Comment by stchang** [comment]
Ok I can fix the position.

**Comment by rfindler** [comment]
Thanks!

**Comment by stchang** [comment]
Now:

`(meth1 "1" 'notAA 5 #:reqkw 4)`
=>
```
meth1: contract violation:
expected: AA?
given: 'notAA
argument position: 2nd
other arguments...:
  a: "1"
  c: 5
  d (optional): 'default-arg4574
  e (optional): 'default-arg4574
  #:reqkw: 4
  #:optkw (optional): 'default-arg4574
```

**Comment by rfindler** [comment]
Very nice! :)

**Pull request closed without merging**
