### PR TITLE
syntax-parse: keep more srcloc info in attribute bindings

### PR DESCRIPTION
**Pull request by AlexKnauth**
to cooperate more with DrRacket check-syntax arrows

### CODE REVIEW

**Comment by AlexKnauth** [comment]
Ok I'll try that.

**Comment by AlexKnauth** [comment]
@rmculpepper 
Does this look better?

**Comment by AlexKnauth** [comment]
A screenshot:
screen shot 2015-06-23 at 12 56 43 am

**Comment by AlexKnauth** [comment]
?

**Comment by stamourv** [comment]
LGTM, will merge.

**Comment by stamourv** [comment]
Merged, thanks!

**Pull request closed without merging**
