### PR TITLE
Add writeln and println functions to complement displayln

### PR DESCRIPTION
**Pull request by lexi-lambda**
This is a fairly simple addition. It just adds `writeln` and `println` functions which simply do `write` or `print` followed by `newline`, respectively, similar to `displayln`'s relationship to `display`.

Considering `displayln` already exists, and I frequently find myself writing `(printf "~v\n" foo)` for debugging purposes, I think this would be a convenient addition to the language.

### CODE REVIEW

**Comment by soegaard** [comment]
I think write feels left out :-)

**Comment by lexi-lambda** [comment]
@soegaard True. Perhaps I should add `writeln` while I'm at it? :)

**Comment by soegaard** [comment]
I'd like that.

**Comment by lexi-lambda** [comment]
@soegaard Okay, I added `writeln` as well. I also tweaked the `println` documentation a little to indicate that users looking for an equivalent to Java's `println` should use `displayln` instead, to avoid confusion.

**Comment by samth** [comment]
I think this needs some tests.

**Comment by lexi-lambda** [comment]
I'm going to close this, not because I don't want to add test, but because I don't think this is actually all that important. For debugging, using `pretty-print` makes much more sense anyway, making this less relevant.

**Comment by samth** [comment]
I actually think we should do this -- I've missed these functions before.

**Comment by samth** [comment]
I've merged this.

**Pull request closed without merging**
